version: '3'
services:
  openlaboratory:
    image: openlaboratory/community
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
