name: Update Forked Repository

on:
  workflow_dispatch: # Allows manual runs
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2 AM UTC; adjust as needed

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the forked repo
      - name: Checkout forked repository
        uses: actions/checkout@v3
        with:
          ref: main

      # Step 2: Set up the git environment
      - name: Set up Git
        run: |
          git config --global user.name "open-laboratory-official"
          git config --global user.email "team@openlaboratory.ai"

      # Step 3: Remove the existing source folder to prepare for fresh copy
      - name: Clean source folder
        run: |
          rm -rf source
          mkdir -p source

      # Step 4: Clone the original repository outside the source folder
      - name: Clone upstream repository
        run: |
          git clone --depth 1 https://github.com/lllyasviel/stable-diffusion-webui-forge.git upstream-temp

      # Step 5: Copy files into the source folder
      - name: Copy upstream files
        run: |
          cp -r upstream-temp/* source/
          rm -rf upstream-temp

      # Step 6: Commit the changes (if there are any)
      - name: Commit changes
        run: |
          git add source
          if ! git diff --cached --quiet; then
            git commit -m "Sync with upstream repository"
          fi

      # Step 7: Push the changes back to the forked repo
      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/underhill-ai/stable-diffusion-webui-forge.git
          git push origin main