name: Update Forked Repository

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the forked repo without modifying top-level files
      - name: Checkout forked repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git and add upstream remote
        run: |
          git config --global user.name "open-laboratory-official"
          git config --global user.email "team@openlaboratory.ai"
          git remote add upstream https://github.com/lllyasviel/stable-diffusion-webui-forge.git
          git fetch upstream main

      # Step 2: Advance commit history to match upstream without changing files
      - name: Fast-forward main branch to match upstream
        run: |
          git merge --ff-only upstream/main || echo "Already up to date with upstream"

      # Step 3: Clone upstream repository into a temporary directory for src updates
      - name: Clone upstream repository for src updates
        run: |
          git clone --depth 1 https://github.com/lllyasviel/stable-diffusion-webui-forge.git temp-upstream

      # Step 4: Sync only src directory
      - name: Sync upstream to src directory
        run: |
          rsync -a --delete temp-upstream/ src/

      # Step 5: Clean up the temporary clone
      - name: Remove temporary folder
        run: rm -rf temp-upstream

      # Step 6: Commit changes only if src directory has updates
      - name: Commit changes
        run: |
          git add src
          if ! git diff --cached --quiet; then
            git commit -m "Update src with latest upstream code"
          fi

      # Step 7: Push changes to the forked repository
      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main