name: Update Forked Repository

on:
  workflow_dispatch: # Allows manual runs
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2 AM UTC; adjust as needed

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest

    steps:
      # Set up the git environment
      - name: Set up Git
        run: |
          git config --global user.name "open-laboratory-official"
          git config --global user.email "team@openlaboratory.ai"

      # Remove the existing src folder to prepare for fresh copy
      - name: Clean src folder
        run: |
          rm -rf src
          mkdir -p src

      # Clone the original repository outside the src folder
      - name: Clone upstream repository
        run: |
          git clone --depth 1 https://github.com/lllyasviel/stable-diffusion-webui-forge.git upstream-temp

      # Copy files into the src folder
      - name: Copy upstream files
        run: |
          cp -r upstream-temp/* src/
          rm -rf upstream-temp

      # Commit the changes (if there are any)
      - name: Commit changes
        run: |
          git add src
          if ! git diff --cached --quiet; then
            git commit -m "Sync with upstream repository"
          fi

      # Push the changes back to the forked repo
      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/underhill-ai/stable-diffusion-webui-forge.git
          git push origin main